In [1]:
import numpy as plt
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("train.txt",sep= ';',header = None,names = ['text','emotion'])

In [3]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [4]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [5]:
unique_emotions = df['emotion'].unique()
emotion_numbers = {}
i = 0
for emo in unique_emotions:
    emotion_numbers[emo] = i
    i +=1

df['emotion'] = df['emotion'].map(emotion_numbers)

In [6]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [7]:
df['text'] = df['text'].apply(lambda x : x.lower())

In [8]:
import string

def remove_punc(txt):
    return txt.translate(str.maketrans('', '', string.punctuation))

df['text'] = df['text'].apply(remove_punc)

In [9]:
df['text'] = df['text'].apply(remove_punc)

In [10]:
def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_numbers)

In [11]:
def remove_emojis(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_emojis)

In [12]:
import sys
!{sys.executable} -m pip install nltk

Requirement already satisfied: nltk in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (3.9.3)
Requirement already satisfied: click in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from nltk) (2025.8.29)
Requirement already satisfied: tqdm in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\dell\appdata\local\programs\python\python310\lib\site-packages (from click->nltk) (0.4.6)

WARNING: Ignoring invalid distribution -ip (c:\users\dell\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\users\dell\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\users\dell\appdata\local\programs\python\python310\lib\site-packages)

In [13]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [14]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

# Stopwords are very common words in a language that usually don’t add much meaning to a sentence and are often removed during text processing.

In [15]:
stop_words = set(stopwords.words('english'))
len(stop_words)

198

In [16]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [17]:
def remove(txt):
    words = word_tokenize(txt)
    cleaned = []
    for i in words:
        if not i in stop_words:
            cleaned.append(i)
    return' '.join(cleaned)

In [18]:
df['text'] = df['text'].apply(remove)

In [19]:
df.loc[1] ['text']

'go feeling hopeless damned hopeful around someone cares awake'

# Bag of Words

In [20]:
""" 
from sklearn.feature_extraction.text import CountVectorizer

documents = [
    "I like pizza",
    "Pizza is the best",
    "I love pasta",
    "Pasta is great"
]

vectorizer = CountVectorizer(ngram_range = (3,3))

X = vectorizer.fit_transform(documents)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("Vectorized Data:\n", X.toarray())
 """

' \nfrom sklearn.feature_extraction.text import CountVectorizer\n\ndocuments = [\n    "I like pizza",\n    "Pizza is the best",\n    "I love pasta",\n    "Pasta is great"\n]\n\nvectorizer = CountVectorizer(ngram_range = (3,3))\n\nX = vectorizer.fit_transform(documents)\n\nprint("Vocabulary:", vectorizer.get_feature_names_out())\nprint("Vectorized Data:\n", X.toarray())\n '

In [21]:
""" 
from sklearn.feature_extraction.text import TfidfVectorizer

documents = [
    "I like pizza",
    "Pizza is the best",
    "I love pasta",
    "Pasta is great"
]

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(documents)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("Vectorized Data:\n", X.toarray())
 """

' \nfrom sklearn.feature_extraction.text import TfidfVectorizer\n\ndocuments = [\n    "I like pizza",\n    "Pizza is the best",\n    "I love pasta",\n    "Pasta is great"\n]\n\nvectorizer = TfidfVectorizer()\n\nX = vectorizer.fit_transform(documents)\n\nprint("Vocabulary:", vectorizer.get_feature_names_out())\nprint("Vectorized Data:\n", X.toarray())\n '

In [22]:
df.head()

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.20, random_state=42)

In [24]:
X_train

676      refers course though cant help feeling somehow...
12113                im starting feel im suffering fatigue
7077     feel like probably would liked book little bit...
13005                                  really feel awkward
12123    im feeling little grumpy today lame weather te...
                               ...
13418    love leave reader feeling confused slightly de...
5390                                         feel delicate
860                          starting feel little stressed
15795             feel stressed tired worn shape neglected
7270         feel someone rude wrongly done something lose
Name: text, Length: 12800, dtype: object

In [25]:
df.shape

(16000, 2)

In [26]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)


nb_model = MultinomialNB()
nb_model.fit(X_train_bow, y_train)


pred_bow = nb_model.predict(X_test_bow)
print(accuracy_score(y_test, pred_bow))

0.7678125

In [27]:
pred_bow

array([0, 5, 0, ..., 5, 5, 0], dtype=int64)

In [28]:
y_test

8756     0
4660     5
6095     0
304      5
8241     0
        ..
15578    5
5746     5
6395     5
7624     5
15245    0
Name: emotion, Length: 3200, dtype: int64

In [29]:
tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)


nb2_model = MultinomialNB()
nb2_model.fit(X_train_tfidf,y_train)

MultinomialNB()

In [30]:
y_pred = nb2_model.predict(X_test_tfidf)

In [31]:
print(accuracy_score(y_test, y_pred))

0.6609375

In [32]:
from sklearn.linear_model import LogisticRegression

In [33]:
logistic_model = LogisticRegression(max_iter=1000)

In [34]:
logistic_model.fit(X_train_tfidf,y_train)

LogisticRegression(max_iter=1000)

In [35]:
log_pred = logistic_model.predict(X_test_tfidf)

In [36]:
print(accuracy_score(y_test,log_pred ))

0.8615625

In [37]:
import pickle

pickle.dump(logistic_model, open("model.pkl", "wb"))
pickle.dump(tfidf_vectorizer, open("vectorizer.pkl", "wb"))